[package]
name = "game_of_life"
version = "0.1.0"
authors = ["mason"]

[[bin]]
name = "game_of_life"
doc = false

[dependencies]
ctrlc = { version = "3.0", features = ["termination"] }
getopts = "0.2"
ncurses = { version = "5.88.0", features = ["wide"] }
